ASSUME CS:CODE,  DS: DATA 

DATA SEGMENT
    COUNT DB ?
    STATE DB ?
DATA ENDS

CODE SEGMENT
START:
    ;INITIALIZE 8254
    ;USE 8254 TO COUNT 10(CNT2), THEN COUNT TO 4(CNT3)
    ;AUTOMATICALLY INITIALIZED
INITIALIZE_8254:
    MOV AL, 00110100B ;cnt0, write16b, method010, not bcd
    OUT 46H, AL
    MOV AL, 01110101B ;CNT1, WRITE16B, METHOD010, BCD
    OUT 46H, AL
    MOV AX, 2710H ;INITIALIZE CNT0
    OUT 40H, AL
    MOV AL, AH
    OUT 40H, AL
    MOV DX, 1 ;STORE 1,2,3,4 AS THE CURRENT STATUS


SCENE_1_3_INITIALIZE:
    MOV AX, 1000H ;INITIALIZE CNT1 TO 10 SECONDS
    OUT 42H, AL
    MOV AL, AH
    OUT 42H, AL
    CMP CX, 1
    JZ SCENE_1
    JMP SCENE_3


SCENE_2_4_INITIALIZE:
    MOV AX, 0400H ;INITIALIZE CNT1 TO 4 SECONDS
    OUT 42H, AL
    MOV AL, AH
    OUT 42H, AL

SCENE_1:
    ;set G1, R2 on
    MOV AL, 01H
    OUT 00H, AL ;G1
    MOV AL, 02H
    OUT 02H, AL ;R2
    ;READ CURRENT COUNT. SHOW THE HIGH DIGITS ON SGN
    

SCENE_2:
SCENE_3:
SCENE_4:




SERVICE PROC FAR ;INTERRUPT
    PUSHA
    PUSH DS
    STI
    ; MAIN()
    CLI
    MOV AL, 20H
    OUT 20H, AL
    POP DS
    POPA
    IRET
SERVICE ENDP

END START